# fly.toml app configuration file generated for tsoha-golfcourses on 2023-09-25T13:04:33+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "tsoha-golfcourses"
primary_region = "arn"

[build]
  builder = "paketobuildpacks/builder:full"

[env]
  PORT = "5000"

[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
